{% set name = "ooouno" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ooouno-{{ version }}.tar.gz
  sha256: 8346b0e87305aa7f12cf8d21b35d32bc671bcddedf9aba4b58c2c02297739ef8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - ooo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Amourspirit/python-ooouno
  summary: Interfaces and classes for LibreOffice (uno)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Amourspirit
